### ISSUE TITLE
Not handling indexed image correctly

### ISSUE THREAD

**Issue by peterwilliams97** [unidoc/unidoc#101]
[legislative-process-poster-espanol.pdf](https://github.com/unidoc/unidoc/files/1199164/legislative-process-poster-espanol.pdf)

32 0 obj
<</BitsPerComponent 8/ColorSpace 15 0 R/Decode[0.0 255.0]

15 0 obj
[/Indexed/DeviceCMYK 117 45 0 R]

UniDoc processes Im0 (obj 32) as a CMYK image

**Comment by gunnsth** [comment]
I believe this has been fixed in commit e2bfa9094a6248b0f40aaf1ca614c81e2fa484cc
Please verify.
