### ISSUE TITLE
pdf_describe range checks on Lab color L=49.8 on PDF Adobe Reader accepts

### ISSUE THREAD

**Issue by peterwilliams97** [unidoc/unidoc#102]
[adobe-sign-technical-overview-au.pdf](https://github.com/unidoc/unidoc/files/1199199/adobe-sign-technical-overview-au.pdf)

**Comment by gunnsth** [comment]
This file appears to have multiple errors.

GS outputs some errors on this:
Page 2
+ ./base/saes.c:176: s_aes_process(): aes stream isn't a multiple of 16 bytes
+ ./base/saes.c:176: s_aes_process(): aes stream isn't a multiple of 16 bytes
   **** Error: Short look-up table in the Indexed color space was padded with 0's.
               Output may be incorrect.
...

go run pdf_all_objects.go ~/pdfdb/adobe-sign-technical-overview-au.pdf >/tmp/1
Error: AES buf length not multiple of 16 (266)
Seems like the encryption is incorrectly handled also.

As for the failure with the color.  Appears to occur with the Lab input as suggested in the title.

@peterwilliams97   Have you had any other issues with Lab colorspaces or encountered them in general?

**Comment by peterwilliams97** [comment]
I ran pdf2ps on adobe-sign-technical-overview-au.pdf then ran pdf2ps on the output and got the attached pdf which looks like the original. It appears that Ghostscript ignores all the encryption errors and gives a reasonable result
[adobe.gs.pdf](https://github.com/unidoc/unidoc/files/1203962/adobe.gs.pdf) 

It's a lot of work to tolerate all the PDF errors that Ghostscript and Adobe tolerate. There is no hurry from us to fix this.

It is interesting that Adobe PDF documents (like this one) contain errors that Adobe PDF tools tolerate.

**Comment by peterwilliams97** [comment]
Your Lab range looks wrong
That Lab value that fails is 49.8039 69 55

      ```
        l := vals[0]
	if l < 0.0 || l > 1.0 {
```
https://en.wikipedia.org/wiki/Lab_color_space#Range_of_coordinates says
L: 0..100
a: −128 .. +127 
b: −128 .. +127

**Comment by gunnsth** [comment]
Actually in the standard the a*, b* are by default in the range [-100, 100] unless overridden by the colorspace's Range entry.  I modified in accordance with that, also taking the Range into account.

I believe these are the values to be specified when specifying with the color via an operand in the content stream such as:
l* a* b* scn (operand).

However, when working with an image represented by Lab colorspace, then each component is normalized by dividing by 2^bits and then extended to the range specified by the Image's Decode entry.  Probably falling back to the colorspace's Range entry if Decode is not specified.
At any rate, that is the approach I am going to take with this and more tests will prove this correct or incorrect.

**Comment by gunnsth** [comment]
The lab range issue has been tackled in 144fa3f75be7cab29ecd8d3bfb9673fcc649f372
also improving color component handling in Separation colorspace.

**Comment by gunnsth** [comment]
I believe this issue has been fixed, closing.
