### ISSUE TITLE
Alignment of added text different between scanned and native PDF

### ISSUE THREAD

**Issue by h-teske** [unidoc/unidoc#110]
Hi,

I used your example script to add text to my PDF. Unfortunately I see differences when adding the text with the same positioning to a native and scanned PDF. With the scanned PDF the text gets rotated and put to the bottom left instead of the top left - see thumbnails.

Any help would be highly appreciated.

Many thanks in advance,
Holger

Native: 
![native](https://user-images.githubusercontent.com/1705660/29071921-f7eeee5c-7c45-11e7-87dd-c41de664ab1a.jpg)
Scanned:
![scanned](https://user-images.githubusercontent.com/1705660/29071920-f7edef16-7c45-11e7-9430-4d74ccb79c04.jpg)

**Comment by gunnsth** [comment]
Hi Holger,

Can you please share the PDF you are applying to?  Preferably by attaching here, or emailing support@unidoc.io if private.

By the first looks, it appears to me that the "scanned page" is rotated by -90 degrees.  That could be done by the scanning program.
To make sure this always works, then need to either rotate the text, or rotate the page to make sure that the behavior is consistent.

I will confirm the diagnosis once I have the file.

**Comment by gunnsth** [comment]
I created an example of how to do handle the rotation flattening:
https://github.com/unidoc/unidoc-examples/blob/master/pdf/pages/pdf_rotate_flatten.go

You would be able to add text as you had planned after drawing the page block.
