### ISSUE TITLE
uniDoc now not support Japanese encoding & decoding

### ISSUE THREAD

**Issue by jimwei** [unidoc/unidoc#115]
Hi,
i find that the uniDoc now not support Japanese encoding & decoding, when it can support?

thanks!

**Comment by gunnsth** [comment]
At the moment this feature is on a backlog with many other features (PDF specs are pretty vast).  We may or may not prioritise its development depending on our customers' needs.  So far it has not come up.

Of course it is a feature we would love to have.  If there is any interest in adding it to the library we would happily add it via a pull request.

**Comment by gunnsth** [comment]
After looking briefly into this, the most obvious way is to implement this for TrueType TTF fonts.

The major work involved 
- Capture the (3,0) subtable from the TTF.
- Capture the (1,0) subtable from the TTF.

May need to adjust the TextEncoder interface to allow 16 bit character codes.  Possibly make character codes more generic.

Create a new TextEncoder implementation that can use those subtables to implement the interface.

**Comment by jimwei** [comment]
Thank you for your reply.
I will try gopdf as a replace.
________________________________
发件人: Gunnsteinn Hall <notifications@github.com>
发送时间: 2017年8月26日 0:44:06
收件人: unidoc/unidoc
抄送: Wei YaPeng (Jim); Author
主题: Re: [unidoc/unidoc] uniDoc now not support Japanese encoding & decoding (#115)


After looking briefly into this, the most obvious way is to implement this for TrueType TTF fonts.

The major work involved

  *   Capture the (3,0) subtable from the TTF.
  *   Capture the (1,0) subtable from the TTF.

May need to adjust the TextEncoder interface to allow 16 bit character codes. Possibly make character codes more generic.

Create a new TextEncoder implementation that can use those subtables to implement the interface.

―

**Comment by gunnsth** [comment]
Sure.  I will close this thread for now and will comment on it when the support has been added.
We are already starting to look into this.

**Comment by gunnsth** [comment]
We have added initial support for composite fonts, which works with unicode TTF fonts.  This work is in branch compositefonts.  It will be merged into the main branch when we feel it is ready and ensure it does not break the API.

There are a couple of test cases demonstrating this in creator_test.go, see:
```
TestParagraphChinese
TestParagraphUnicode
```
for examples of text with unicode characters.

The composite font is loaded via `NewCompositePdfFontFromTTFFile` function.

I would appreciate if you would test it out and give us some feedback.

Best,
Gus

**Comment by jimwei** [comment]
Hi,

I have test the Japanese encoding & decoding via MS Gophic TTF file, and the result is cool.

Another question is, in windows, the MS Gophic file is TTC, not TTF, if I want to use the font, I should only export TTF from TTC. Can unidoc suppor ttc file?


Thank you very much!

Best regards!

________________________________
发件人: Gunnsteinn Hall <notifications@github.com>
发送时间: 2017年9月1日 21:25:04
收件人: unidoc/unidoc
抄送: Wei YaPeng (Jim); Author
主题: Re: [unidoc/unidoc] uniDoc now not support Japanese encoding & decoding (#115)


We have added initial support for composite fonts, which works with unicode TTF fonts. This work is in branch compositefonts. It will be merged into the main branch when we feel it is ready and ensure it does not break the API.

There are a couple of test cases demonstrating this in creator_test.go, see:

TestParagraphChinese
TestParagraphUnicode


for examples of text with unicode characters.

The composite font is loaded via NewCompositePdfFontFromTTFFile function.

I would appreciate if you would test it out and give us some feedback.

Best,
Gus

―

**Comment by gunnsth** [comment]
Excellent.

At the moment, TTC is not supported, but plan to add a feature to allow using fonts from TTC.  Essentially TTC is just a bunch of TTF fonts (like a directory sort of).  So there will be a new function to load font from TTC, also specifying an index to pick which font to use.  Also helper function to get list of all the fonts (with name and index) from the TTC.

Another thing is font subsetting.  Given how large the TTF font files can be, we are also looking to add font subsetting.  That way we can choose to use only the characters that are actually present in the PDF, which will lead to much smaller file sizes.
What kind of file sizes were you getting when you tested it out?

Regards,
Gus

**Comment by jimwei** [comment]
Hi, Gus

the size of the MS gophic ttf font file i used is about 7MB(7035KB).


Regards,

Jim

________________________________
发件人: Gunnsteinn Hall <notifications@github.com>
发送时间: 2017年9月5日 18:14:18
收件人: unidoc/unidoc
抄送: Wei YaPeng (Jim); Author
主题: Re: [unidoc/unidoc] uniDoc now not support Japanese encoding & decoding (#115)


Excellent.

At the moment, TTC is not supported, but plan to add a feature to allow using fonts from TTC. Essentially TTC is just a bunch of TTF fonts (like a directory sort of). So there will be a new function to load font from TTC, also specifying an index to pick which font to use. Also helper function to get list of all the fonts (with name and index) from the TTC.

Another thing is font subsetting. Given how large the TTF font files can be, we are also looking to add font subsetting. That way we can choose to use only the characters that are actually present in the PDF, which will lead to much smaller file sizes.
What kind of file sizes were you getting when you tested it out?

Regards,
Gus

―

**Comment by itcuihao** [comment]
Hi, Gus
you say,
> There are a couple of test cases demonstrating this in creator_test.go, see:
```
TestParagraphChinese
TestParagraphUnicode
```
Sorry,I did not see  the `TestParagraphChinese`  in creator_test.go.

**Comment by gunnsth** [comment]
@itcuihao This work is currently only in branch compositefonts.
See https://github.com/unidoc/unidoc/tree/compositefonts

It will be merged into the main branch when we feel it is fully ready and ensure it does not break the API.

**Comment by itcuihao** [comment]
@gunnsth thank you for your reply.

**Comment by gunnsth** [comment]
Closing this as already implemented in v3.  Font subsetting is tracked in #118  which will give smaller file size for large fonts.

**Comment by xiong425** [comment]
I have tested on the page paragraph, It is worked. But it didn't worked on the table cell if you use the Chinese.

**Comment by gunnsth** [comment]
@xiong425 Are you on branch v3?
Can you post a standalone example so the problem can be reproduced?
