### ISSUE TITLE
Font kerning / character spacing

### ISSUE THREAD

**Issue by KeeTraxx** [unidoc/unidoc#119]
Hello I'm currently evaluating unidoc for PDF generation purposes.

I need to be able to set character spacing (also known as kerning) for some paragraphs.
Is that currently possible? I haven't found anything in the API or the examples.

Thanks for any pointers!

**Comment by gunnsth** [comment]
Hi,
Are you only trying to adjust character spacing (uniformly) or only for certain glyphs?
Can you give an example for how you think the API should be for what you need?

There is some work underway to improve font support, see related tickets #115, #116 #118.
I believe kerning is to control spacing between certain glyphs, not paragraphs?
To add spacing between paragraphs you can add a margin.  Or it can also be possible to set a specific PDF parameter such as Tc (character spacing) which can automatically increase the spacing between all characters in a paragraph.  Note that that is not exactly the same as kerning (which is defined by the font program).

**Comment by KeeTraxx** [comment]
Hi

I'm actually trying to adjust character spacing uniformly, i.e. for all glyphs. The Tc PDF parameter should suffice for that matter.

Is there a simple example of how to set the Tc Parameter for a new PDF using Unidoc?
I couldn't find a way to do it.

```
pdf := creator.New()
pdf.SetPageSize(creator.PageSizeA4)

p := creator.NewParagraph("hello")
// How to set Tc for Paragraph p?

pdf.Draw(p)

```

**Comment by gunnsth** [comment]
Thanks.  Unfortunately this is not possible at the moment.  It is fairly easy to do, it requires
- Setting the Tc operand in the PDF
- Accounting for the adjusted character spacing in wrapping calculations

I will add it to our plans for future updates in the creator.

**Comment by gunnsth** [comment]
@KeeTraxx Can you check if #338 addresses this?
