### ISSUE TITLE
Cell : ability to chose sides for borders

### ISSUE THREAD

**Issue by mrsinham** [unidoc/unidoc#120]
I'm on a billing project and chose Unidoc for PDF rendering. After a few tests, I found that only box or unboxed borders are allowed on cells.

So if you want to do stuff like this :

![billing](http://kb.bqe.com/images/billing%20schedule%20report.png)

This is not possible. How far is the ability to draw borders only on chosen sides ?

Thank you for all the work already done.

**Comment by gunnsth** [comment]
Thanks for the request. The plan is indeed to add more flexible borders such as you mention.  It is pretty high on our priority list for improving the creator.  I cannot tell how far out it is at present but I expect it will be a part of next series of updates in the creator.

**Comment by gunnsth** [comment]
PS. If your customer has purchased a UniDoc license with support you can ask him to contact us as this involves support which can be to prioritise needed features.

**Comment by mrsinham** [comment]
Cool, thanks for the answer.

**Comment by gunnsth** [comment]
This is now supported in branch v3 (upcoming version 3.0 release), via SetBorder method
https://github.com/unidoc/unidoc/blob/b6de33b79c8b32d4b299ee654e7ef86847efec38/pdf/creator/table.go#L563
Please test, ticket will be closed once merged into master.

**Comment by mrsinham** [comment]
Thanks a lot. Sadly, I don't work anymore on the project that needed that stuff but I think PDF is not very far away in a career. So thx !
