### ISSUE TITLE
Text extraction - line height sensitivity/tolerance

### ISSUE THREAD

**Issue by mdelorimier** [unidoc/unidoc#122]
Hello,

I am extracting text from a pdf and in most cases, text that is on one line in two diffrent blocks in the PDF ends up on two diffrent lines.

Would there be a way to configure the extractor's tolerances as far as vertical positionning of blocks in the page?

Regards :)

**Comment by gunnsth** [comment]
Hi,

Currently there is not support for this.  The text extraction currently offered is pretty primitive.
We have plans to add more powerful text extraction, both supporting unicode text and allowing extracting text with their coordinates. Also extracting text within certain locations (so can specify a template to extract text from certain fields).  I imagine your task could be solved with such support.

Generally our efforts are driven by need, both our own needs in other projects, as well as needs from our customers when we do contracting work to accomplish certain tasks.

I hope that helps to answer your question. Let me know if there is anything I can clarify.

**Comment by mdelorimier** [comment]
Hello,

Thanks for the clarification.
If you need code for unicode extraction, i did come up with something that seems to work well.

Regards :)

**Comment by gunnsth** [comment]
Cool.  If you would be willing to share that, that would be awesome.

Is it an isolated code that could be committed into our example repository, i.e. https://github.com/unidoc/unidoc-examples 
or more of an isolated package?

Regards, GH.

**Comment by gunnsth** [comment]
Related https://github.com/unidoc/unidoc/pull/124

**Comment by gunnsth** [comment]
@mdelorimier Are you willing to share the unicode extraction code? Looking to add support for that soon via the ToUnicode CMaps.

**Comment by mdelorimier** [comment]
@gunnsth Yes, sorry about the long delay. I will gather the code i have used and submit a PR i guess?

**Comment by gunnsth** [comment]
@mdelorimier That would be excellent.

**Comment by gunnsth** [comment]
We also have a preliminary implementation of unicode support for text extraction in our new extractor package.  Hopefully we can combine the efforts to get the best quality text extraction, see one example on
https://github.com/unidoc/unidoc-examples/blob/master/pdf/text/pdf_extract_text.go

**Comment by gunnsth** [comment]
@peterwilliams97 What do you think about this?  Is this issue still applicable?

**Comment by peterwilliams97** [comment]
We now use a tolerance of `0.2 x font height` for sorting text by y position. 

```
// ToText returns the contents of `tl` as a single string.
func (tl TextList) ToText() string {

	fontHeight := tl.height()
	// We sort with a y tolerance to allow for subscripts, diacritics etc.
	tol := minFloat(fontHeight*0.2, 5.0)
      ....
```
This seems to work well in my testing but I could imagine there being problems with subscripts and superscripts. If you have a test PDF file that our new text extraction doesn't work on then please submit it and I will take a look.

**Comment by gunnsth** [comment]
OK. Will close for now, if there is a bug can reopen with specific cases.
