### ISSUE TITLE
find and replace

### ISSUE THREAD

**Issue by joeblew99** [unidoc/unidoc#123]
I am experimenting with this li so that i can take a PDF written in English and Translate it to another language.

I am however now sure about if this lib will allow me to do find and replace, so that if the replaced text is longer or shorter all the elements around it will adjust.

Its in general a pretty hard problem, and to be frank i am not sure if PDF is the write medium..
Might be better to do it in word..

**Comment by gunnsth** [comment]
Hi.

Yes, you are correct.  It is not a straightforward task and you will need to handle both line wrapping and wrapping to the next page also.

Especially challenging if the file input can just be any PDF file, i.e. does not have a fixed format.

So far we do have pretty primitive support for extracting text from PDFs.  However, unicode mappings are currently not supported.  There is ongoing effort to improve this along with our effort to support writing unicode characters (compositefonts branch).

We may add a special package dedicated to text extraction, allowing to extract text along with coordinates as well as extracting text from specific locations in PDF.

Generally our efforts are driven by need, both our own needs in other projects, as well as needs from our customers when we do contracting work to accomplish certain tasks.

I hope that helps to answer your question.  Let me know if there is anything I can clarify.

**Comment by gunnsth** [comment]
Same as #16
