### ISSUE TITLE
Background color?

### ISSUE THREAD

**Issue by j8** [unidoc/unidoc#125]
How can I add different background on every page using the creator?

**Comment by gunnsth** [comment]
Hi.  Background can be added to a page by drawing a rectangle filling the area at the beginning of each page.

For example:
```
	c := creator.New()

	c.NewPage()

	bgColor := creator.ColorRGBFromHex("#cccccc")

	rect := creator.NewRectangle(0, 0, c.Width(), c.Height())
	rect.SetFillColor(bgColor)
	c.Draw(rect)

	// Add the rest of the contents..
```

I hope that helps address your question.

Best,
Gus
