### ISSUE TITLE
Does cell content support auto wrap long text

### ISSUE THREAD

**Issue by Kiennh** [unidoc/unidoc#134]
Hi,
Does unidoc report support auto wrap a very long text on a cell content.
I tried pdf_report.go, add a very long text to issue table like
```
        p = creator.NewParagraph("Klapparstig 16, 101 Reykjavik, Iceland Klapparstig 16, 101 Reykjavik, Iceland Klapparstig 16, 101 Reykjavik, Iceland Klapparstig 16, 101 Reykjavik, Iceland Klapparstig 16")
	p.SetFont(fontRegular)
	p.SetFontSize(10)
	p.SetColor(pColor)
	p.SetMargins(0, 0, 5, 0)
	p.SetTextAlignment(creator.TextAlignmentLeft)

	cell = issuerTable.NewCell()
	cell.SetBorder(creator.CellBorderStyleBox, 1)
	cell.SetContent(p)
```
The pdf output show me only single line of text with some missing character
Does unidoc support cell of a table like this ? or any other options is required?

**Comment by gunnsth** [comment]
Wrapping in table cells is currently only partially handled.  Paragraphs have an automatic wrapping feature that is disabled when adding to a table cell.  It can be re-enabled with a workaround, and the row height set manually to compensate.

The code would look something like

```
p = creator.NewParagraph("Klapparstig 16, 101 Reykjavik, Iceland Klapparstig 16, 101 Reykjavik, Iceland Klapparstig 16, 101 Reykjavik, Iceland Klapparstig 16, 101 Reykjavik, Iceland Klapparstig 16")

	cell := priTable.NewCell()
	// Enable wrap for width calculation.
	p.SetEnableWrap(true)
	// Set paragraph width for height calculation.
	p.SetWidth(cell.Width(c.Context()))
	// Set the row height based on the paragraph.
	priTable.SetRowHeight(priTable.CurRow(), p.Height()*1.0)
	cell.SetBorder(creator.CellBorderStyleBox, 1)
	cell.SetContent(p)
	// Set enable wrap (it is set to false after adding to cell content).
	p.SetEnableWrap(true)
	sc.Add(priTable)
```
and output look like
![image](https://user-images.githubusercontent.com/50777/34392508-76ae8488-eb44-11e7-9725-007792ac63ba.png)

Probably need to work a bit with the margins to make it look right.  

This is an item to be addressed in the next major iteration for the creator package.  It should be enough to enable wrapping and have everything else taken care of automatically.

**Comment by Kiennh** [comment]
thank you so much, it's clear now
