### ISSUE TITLE
enhance? possible to insert pdf page like insert image

### ISSUE THREAD

**Issue by ghiewa** [unidoc/unidoc#136]
why I ask so, is come from real problem how to impose pdf into one 'big' plate page. is it possible? or any functionality I didn't discovered?

thanks advance.

**Comment by gunnsth** [comment]
Hi,

Yes.  You can load PDFs as a template and apply to a new one with the creator package.
For example with creator.NewBlockFromPage can convert a model.PdfPage to a block that can be drawn with the creator,
For an example how to load the block, see for example 
https://github.com/unidoc/unidoc-examples/blob/a04a8bbc6ea946b4a43e507d8e8395328f70419f/pdf/pages/pdf_rotate_flatten.go

The block can be moved, rotated, scaled and applied anywhere you need.  Let me know if you need a more specific example.

Best,
Gus

From: Moyan
Sent: Friday, January 19, 2018 9:36 AM
To: unidoc/unidoc
Cc: Subscribed
Subject: [unidoc/unidoc] enhance? possible to insert pdf page like insertimage (#136)

why I ask so, is come from real problem how to impose pdf into one 'big' plate page. is it possible? or any functionality I didn't discovered?
thanks advance.

**Comment by ghiewa** [comment]
great! I will try it as you said. thanks

**Comment by ghiewa** [comment]
to close my question. Yes, it works well like gunnsth advised. Great tool!
