### ISSUE TITLE
Positioned Text

### ISSUE THREAD

**Issue by Phisatho** [unidoc/unidoc#137]
Not happy with the quality of built-in chart (wcharczuk/go-chart), I tried to draw my own chart. Everything went well except that I am not able to draw text in the body of the chart. here is what I have achieved so far.
![image](https://user-images.githubusercontent.com/5249964/35187465-8fbef8fc-fe3d-11e7-9483-29be73dde570.png)
whereas this is what I want to achieve.
![image](https://user-images.githubusercontent.com/5249964/35187476-abc1ff90-fe3d-11e7-8e7c-e3e6e61ade17.png)
Is this currently possible or is this a feature request?

**Comment by gunnsth** [comment]
@Phisatho The charting library generates an image which is embedded in the PDF.  In case you want to add the labels onto that image, you may need to open an issue with go-chart.
