### ISSUE TITLE
Add PDF bookmarks (outlines)

### ISSUE THREAD

**Issue by ahall** [unidoc/unidoc#14]
Implement proper high level handling of outlines for reading and writing in package model. 

## Requirements
- API to create new outlines
- Hierarchy can be a tree (chapters, subchapters)
- API to get a list of outlines that is easy to traverse through and print items.

## Proposal (work in progress)
Suggestion for API:
```go
outlines := model.NewOutlines()
dest := model.NewDestination()
dest.Page = page
node := outlines.Add(model.NewOutlineWithDest("Chapter 1", dest))
dest := model.NewDestination()
dest.Page = page2
node := node.Add(model.NewOutlineWithDest("Chapter 1.1", dest2))
```

## Other:
- The API should also make it possible to allow merging of splitting documents with outlines.  For merging, just need to be aware of the page which the bookmark points to and take into account when merging files.  Similar for splitting.

**Comment by gunnsth** [comment]
Related #87
