### ISSUE TITLE
Trouble extracting text from PDF - garbage characters

### ISSUE THREAD

**Issue by kevinburke** [unidoc/unidoc#143]
I have a PDF that was emailed to me by customer support at clippercard.com. It's a version 1.3 PDF.
When I try to extract the text from it, I get garbage out that looks like this.

```
!"#$%#&!'($)*'%!("+),(")
ETDTEDEG00ETHET03L
0JNJJ0
%4>KK8:0%3<P
```

However, if I load the same PDF into Chrome, Mozilla Firefox or Preview.app, the
document renders correctly, with highlightable and searchable text.

Here's the code I am using to extract the text, more or less the sample from the
website.

```go
	pdfReader, err := pdf.NewPdfReader(r)
	if err != nil {
		return nil, err
	}

	numPages, err := pdfReader.GetNumPages()
	if err != nil {
		return nil, err
	}
	pages := make([]string, numPages)
	decoder := charmap.Windows1252.NewDecoder()
	for i := 1; i <= numPages; i++ {
		page, err := pdfReader.GetPage(i)
		if err != nil {
			return nil, err
		}
		contentStreams, err := page.GetContentStreams()
		if err != nil {
			return nil, err
		}
		pageContentStr := ""

		// If the value is an array, the effect shall be as if all of the
		// streams in the array were concatenated, in order, to form a
		// single stream.
		for _, cstream := range contentStreams {
			//fmt.Printf("cstream: %#v\n", cstream)
			pageContentStr += cstream + "\n"
		}

		cstreamParser := pdfcontent.NewContentStreamParser(pageContentStr)
		txt, err := extractText(cstreamParser)
		// ...
	}
```

It would be great if I could extract the actual text that appears on screen when I load the document in Preview.app, rather than the characters printed above.

I'm not sure the best way to send the PDF to you, it contains my history of
rides on my Clipper card and I'd rather not have it made public.

**Comment by gunnsth** [comment]
The best way would be via personal email (e.g. ghall@foxyutils.com).  Otherwise, we can find other PDFs. I am guessing the reason is due to encoding, e.g. using the glyph index rather than e.g. WinAnsiEncoding.  However, if the font has a ToUnicode mapping defined it should be possible to decode. Unfortunately, we are not taking the ToUnicode into account yet.

**Comment by gunnsth** [comment]
This is fixed with enhanced text encoding support in package extractor.  See 
https://github.com/unidoc/unidoc-examples/blob/master/pdf/text/pdf_extract_text.go
for an example
