### ISSUE TITLE
Problem with PdfParser.readTextLine if string contains code points above U+0080

### ISSUE THREAD

**Issue by quetz** [unidoc/unidoc#144]
`readTextLine` consumes reader byte-by-byte and appends read bytes to string, that leads to string length different from actual number of bytes read.
In essense problem is:
```
s := ""
s += string(0xb0)
// at this point len(s) == 2, not 1
```
This leads to all kinds of weird errors because parsing code relies on rolling back string reading like that:
```
parser.SetFileOffset(parser.GetFileOffset() - len(string_we_just_read))
```

**Comment by gunnsth** [comment]
Nice.  Do you have any example PDF files where this issue is encountered?  Would be great, then we can add it to our PDF test bench.  Otherwise the fix is looking good, will look to test it and merge soon.

Best,
Gus

**Comment by quetz** [comment]
It is pretty big file, before fix it failed on `GetNumPages`
I published it in release here: https://github.com/quetz/unidoc/releases/tag/v2.0.1

**Comment by gunnsth** [comment]
Great, thank you.
