### ISSUE TITLE
There are files with *param = "Decode"

### ISSUE THREAD

**Issue by santsai** [unidoc/unidoc#149]
https://github.com/unidoc/unidoc/blob/820be654673c541cc6c72631b68c233b81d45383/pdf/contentstream/inline-image.go#L334

**Comment by gunnsth** [comment]
@santsai Can you send us an example of such file for testing? Either here or share a link.  Would be great for our test corpus.

**Comment by santsai** [comment]
@gunnsth I encounter this when I am trying to code a little tool to rename my bank statement automatically according to its content. So I can't share a sample file to you as it contains personal details.

**Comment by gunnsth** [comment]
@santsai No problem, I fully understand. This is actually pretty common, e.g. slight deviations from the specs.  Will fix it shortly.
