### ISSUE TITLE
Trouble Extracting Texts from PDF

### ISSUE THREAD

**Issue by korusdipl** [unidoc/unidoc#162]
Hi! I looked into the stuffs at issue @ https://github.com/unidoc/unidoc/issues/143 and also tried to use the new extractor, but having trouble PDFs of wierd encodings (I suspect). I hope you to look into it. From some point, the text was composed/printed out wrongfully and from when accessing page 23, the memory usage is skyrocketing.

Thanks again for this great project.

[1313503594_944915.pdf](https://github.com/unidoc/unidoc/files/2173379/1313503594_944915.pdf)

**Comment by gunnsth** [comment]
@korusdipl Thanks for reporting. We are aware of the issue and there is ongoing work that includes more fonts and encoding types. I will add the PDF you submitted to the testing corpus.

**Comment by korusdipl** [comment]
@gunnsth Thanks for your attention! I will wait for the fix to come!

**Comment by gunnsth** [comment]
@korusdipl The extractor now supports this file.

**Comment by korusdipl** [comment]
Thank you so much for the update!
