### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by joanbono** [unidoc/unidoc#164]
Hi Team! 

Is there any way to extract PDF metadata using unidoc library?

I've been checking the examples on website but I've not found anything.

Thanks!

**Comment by gunnsth** [comment]
@joanbono Are you just looking to get the metadata stream as XML and use an external xml parser such as "encoding/xml" ?  Can you specify what information you are looking to retrieve.  If you can post an example of a PDF you are working with, that would be great.

**Reference:**
To give a bit of background here...

According to section 14.3 Metadata (p. 556 in PDF32000_2008) metadata can be stores in two ways:
1. In metadata streams associated with the document or a component of the document (newer, preferred approach)
2. In a document information dictionary associated with the document (old way)

The document information dictionary has fixed field such as:
- Title
- Author
- Creator
- Producer
- Subject
- etc.. see Table 317 p. 558 for full list.  

An example for extracting this information has been posted at
https://github.com/unidoc/unidoc-examples/blob/master/pdf/metadata/pdf_metadata_get_docinfo.go

We will add a separate example for the extraction of XML metadata

**Comment by joanbono** [comment]
This is exactly what I was looking for.

Thanks @gunnsth 👍 

Stay in touch for the XML example

**Comment by gunnsth** [comment]
We have an XML XMP example available as well:
https://github.com/unidoc/unidoc-examples/blob/master/pdf/metadata/pdf_metadata_get_xml.go

I will be closing the ticket, but feel free to comment or let us know if you need other examples or enhancement to the current metadata examples.
