### ISSUE TITLE
Convert PDF to text

### ISSUE THREAD

**Issue by ahall** [unidoc/unidoc#17]

**Comment by ckoepp** [comment]
Any chance on an example for this? I'm actually not sure how to do this.

`PdfPage.GetPageDict()` looks promising. But so far, I was not able to figure out any hint on this use case from the documentation. What struct does actually hold text strings?

**Comment by gunnsth** [comment]
No problem.  The following gist has an example for extracting text from a PDF file:
[example gist](https://gist.github.com/gunnsth/fdc3231e0a7bcb793649a7fc28ffde7b)

This example is based on UniDoc v2 which is currently in alpha (for example tagged release v2.0.0-alpha.1).

Let me know if you have any questions.

Best,
Gus

**Comment by ckoepp** [comment]
thanks for the hint to the v2 branch.

Reading the content stream is actually eating up all resources of my notebook. I'm parsing a document from a document scanner. libpoppler however is able to extract the OCR text in msecs.

Kind of strange 😕

**Comment by gunnsth** [comment]
Any chance you can send me the file you are trying so I can troubleshoot it?

**Comment by ckoepp** [comment]
dropped a message at your gmail inbox

**Comment by gunnsth** [comment]
Thanks.  Please try pulling on branch v2.  Should work now.

**Comment by mzimmerman** [comment]
I have success using this method on most PDFs however have one where I get encoded text out instead.  I noticed the documentation for [ExtractText](https://github.com/unidoc/unidoc/blob/master/pdf/contentstream/contentstream.go#L107) which says it doesn't take encoding into effect.  How do I make it account for that?  It wasn't clear.
