### ISSUE TITLE
Multiple paragraphs in one table cell

### ISSUE THREAD

**Issue by mchusovlianov** [unidoc/unidoc#170]
Hi! Is there a way how to have multiple paragraphs (with different formating like size, font and so on) in one table cell?
![image](https://user-images.githubusercontent.com/196578/42946719-cdc16938-8b95-11e8-9813-94d0a9d4bf74.png)

**Comment by gunnsth** [comment]
We are currently planning to allow Paragraph to have multiple formatting
https://github.com/unidoc/unidoc/issues/84
Would that solve your need?

**Comment by mchusovlianov** [comment]
@gunnsth Yep! That's exactly what we need.

**Comment by gunnsth** [comment]
@mchusovlianov Please try new feature in branch creator-tablecell-div-image-support
You can add multiple Paragraphs to a Division component and add to the TableCell.
Take a look at TestTableWithDiv in table_test.go

**Comment by gunnsth** [comment]
Closed by merge of PR #179 into master (and release of 2.1.1).
