### ISSUE TITLE
Fill in Form Fields

### ISSUE THREAD

**Issue by ahall** [unidoc/unidoc#18]

**Comment by drhoden** [comment]
[Today's merge](https://github.com/unidoc/unidoc/pull/126) resolves this issue.

Before the patch there was no way to pass a populated PdfAcroForm to the underlying PdfWriter that the Creator.Write method uses to write the PDF.  Assuming you have populated your form, call c.SetForms(f) where c is a Creater and f is a PdfAcroForm.

Populating the form is outside the scope of this issue, but I would be happy to explain if needed.

**Comment by gunnsth** [comment]
@drhoden Thanks! If you have any example code that we could place into the unidoc-examples repo, that would be very much appreciated.

**Comment by drhoden** [comment]
@gunnsth I will try to get that to you later today.

**Comment by gunnsth** [comment]
@drhoden If you still have the code, we would appreciate if you can send it to us.  No worries if it needs clean up, we will take care of it and post it to our example repository.
Best, Gus

**Comment by ttaranov** [comment]
I created a possibly related issue a few days ago - https://github.com/unidoc/unidoc-examples/issues/15.

Form filling with the new pdfWriter.SetForms() works ok - it produces a pdf with filled fields. What is not clear to me is how to make a pdf that just has the read-only filled values - and not filled/fillable form fields.

**Comment by gunnsth** [comment]
@ttaranov Currently forms are not fully supported with a convenient high level syntax in unidoc.  You would need to go through the PDF standard and determine what key/value to set in the pdf dictionary for the form field to set to read-only.  Should be fairly trivial to do.

**Comment by gunnsth** [comment]
So far we have capabilities for:
- Creating and adding a new form to a PDF:
https://github.com/unidoc/unidoc-examples/blob/v3/pdf/forms/pdf_form_add.go
- Listing form fields in PDF
https://github.com/unidoc/unidoc-examples/blob/v3/pdf/forms/pdf_form_list_fields.go
- Flattening forms and generating appearance streams if not present
- Merging in FDF form data to fill form
https://github.com/unidoc/unidoc-examples/blob/v3/pdf/forms/pdf_form_fill_fdf_merge.go
https://github.com/unidoc/unidoc-examples/blob/v3/pdf/forms/pdf_form_flatten.go
- Getting field values
https://github.com/unidoc/unidoc-examples/blob/v3/pdf/forms/pdf_form_get_field_data.go

In addition to FDF merge, it's easy to implement filling form via JSON (example to follow).

This functionality is pretty complete in terms of forms. Future work may be to provide higher level functions to work with forms, e.g. #265. Further issues created on this should be specific as the basis is already in place.

**Comment by gunnsth** [comment]
Related #294 
and
https://github.com/unidoc/unidoc-examples/pull/26

**Comment by gunnsth** [comment]
At this point we think there is enough support to close this.  Further issues created on this should be specific as the basis is already in place.
