### ISSUE TITLE
Different styles in one paragraph

### ISSUE THREAD

**Issue by mchusovlianov** [unidoc/unidoc#191]
Hi, guys! Is it possible to have different format in one paragraph,  like:
this is the usual text with **strong** and _italic_  text support?

**Comment by gunnsth** [comment]
This effect can now be achieved by placing multiple Paragraphs into one Division component, in inline mode. See for example:
https://github.com/unidoc/unidoc/blob/8e6553be85e56f4df7e53ca9e723dcd1f5e0a8bb/pdf/creator/division_test.go#L236

We will also be implementing multi styles in a single paragraph as that will give more flexibility for line wrapping, alignment etc, related ticket #200 

Closing.
