### ISSUE TITLE
Compress PDF

### ISSUE THREAD

**Issue by ahall** [unidoc/unidoc#20]
Support reducing the size of PDFs by optimising the output.

**Comment by Lord-Protector** [comment]
Is it real to reduce size manually? PDF from Images is VERY huge. I think because of using raw tiff with slightly compressing by LWZ.

**Comment by gunnsth** [comment]
You could try using JPEG encoding (DCTDecoder).  Also check the pixel dimensions of your image and the dimensions on the page and you can calculate the points per inch resolution (PPI).  Typically PDF resolutions are 72 PPI.

Feel free to post your code so we can give more specific suggestions / code examples.

**Comment by Lord-Protector** [comment]
@gunnsth can you tell more about jpeg encoding? I already use jpeg to create pdf, but even from 3 jpg-photos (every ~50 kb) I got 500 kb pdf file. Also I resized photos to 612 in width, it reduced size, but not enough :(

**Comment by gunnsth** [comment]
The jpeg encoding is implemented with core.DCTDecoder.
How to use it depends on how you are adding the image.  It would be helpful if you can post the code where you are adding the image.  Then we can also figure out what encoding is being used currently.  Sounded like you were using FlateDecode (?).

**Comment by Lord-Protector** [comment]
```golang
// resp.Body() is bytes from GET-request
imgOrig, _, err := image.Decode(bytes.NewReader(resp.Body()))
if err != nil {
	continue
}

imgResized := resize.Resize(612, 0, imgOrig, resize.Bicubic)

img, err := creator.NewImageFromGoImage(imgResized)
if err != nil {
	continue
}
img.ScaleToWidth(612.0)

height := 612.0 * img.Height() / img.Width()

c.SetPageSize(creator.PageSize{612, height})
c.NewPage()

img.SetPos(0, 0)
_ = c.Draw(img)
```
Example image: http://e-library.kai.ru/reader/hu/flipping/Resource-2743/749.pdf/pages/1

**Comment by gunnsth** [comment]
OK.  The creator uses flate encoding by default.
```
// NewImage create a new image from a unidoc image (model.Image).
func NewImage(img *model.Image) (*Image, error) {
	image := &Image{}

	// Create the XObject image.
	ximg, err := model.NewXObjectImageFromImage(img, nil, core.NewFlateEncoder())
...
```

My proposed fix is to add a method
`func (img *Image) SetEncoder(enc StreamEncoder) { ... }
`
so you can do (once added)
`img.SetEncoder(core.NewDCTDecoder())`

Then you can also play around with the JPEG Quality factor (property of the DCTDecoder), which can trade off size vs quality.

I imagine this will improve your file size quite a bit.

I will update the thread when this has been completed.

**Comment by Lord-Protector** [comment]
@gunnsth manually editing lib code and changing encoder gives me empty pdf pages. But just 127 kb :D

**Comment by gunnsth** [comment]
This has been committed to master.

Now you can do something along the lines of:
```
encoder := core.NewDCTEncoder()
encoder.Quality = 90
// Encoder dimensions must match the raw image data dimensions.
encoder.Width = int(img.Width())
encoder.Height = int(img.Height())
img.SetEncoder(encoder)
```

The specified width/height for the encoder should in your case match the resized image dimensions.

**Comment by gunnsth** [comment]
Haha, nice :).  I am guessing you did not set the Width and Height parameters on the encoder.  Unfortunately that is required for it to work properly at the moment!

Will look back later and see if I can make it figure it out on the fly, but this should work for now.

**Comment by Lord-Protector** [comment]
@gunnsth thanks! Just reduced file size from 36 MB to 16 MB. Thanks for so quick reply and help!

**Comment by gunnsth** [comment]
Cool!  No problem.  Thanks for pointing out the issue and helping us improve.

NB. You can probably reduce it further by reducing the Quality factor, but of course only as long as the image is still looking presentable.

**Comment by gunnsth** [comment]
PS. I am closing this thread as it was getting rather stale.  Feel free to open new issues if something similar comes up.

**Comment by Lord-Protector** [comment]
@gunnsth yep, I understand how jpeg-encoding works :) But I already have not so good images, so even on 70-80 quality is dramatic...
