### ISSUE TITLE
Make tests for TTF font parser

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unidoc#203]
# Current state
At the moment we do not have any direct unit tests for ttfparser.go.
Furthermore, it sometimes appears that the information parses is incorrect and leads to errors, in particular when it comes to generation of ToUnicode maps.

# Proposal
1. Create a set of basic test cases parsing mock TTF data that ensures or relevant parts for the different tables of the TTF.
2. Test data parsing of both a minimal TTF file and check that all data is correct.
3. Find edge cases that can be found in fonts for example with FontValidator and check that the parser handles these.
4. Make tests for the tables in FreeSans.TTF which according to Adobe Reader may be invalid (Bad Widths error, related #190 #201)

**Comment by dennwc** [comment]
Relevant: https://github.com/unidoc/unidoc/pull/248

**Comment by dennwc** [comment]
@gunnsth Totally agree. I think we can close this one now.
