### ISSUE TITLE
Silicence Warnings

### ISSUE THREAD

**Issue by jcampbell05** [unidoc/unidoc#207]
Sometimes we don't have control of what PDFs are processed so we need a way of just telling the PDF library to process the document without outputting anything to stderr which may make our application think there was an issue.

If there is a way of letting the library know not to emit these errors then that would be awesome (or at log them to a file).

<img width="800" alt="screen shot 2018-09-20 at 16 29 48" src="https://user-images.githubusercontent.com/1484989/45829315-91431400-bcf2-11e8-8cce-29907e2e47d7.png">

**Comment by gunnsth** [comment]
@jcampbell05 The log level for unidoc can be adjusted.  Typically we recommend using the error log level.  The output can be logged to file or any way you want.  Just need to set the logger which needs to fulfill the common.Logger interface: see for instance
https://github.com/unidoc/unidoc-examples/blob/ed4122c80c507b1fd5a5f5e9c7e709f4fe3a4e82/pdf/testing/pdf_count_color_pages_bench.go#L45

The logger interface is:
```
type Logger interface {
	Error(format string, args ...interface{})
	Warning(format string, args ...interface{})
	Notice(format string, args ...interface{})
	Info(format string, args ...interface{})
	Debug(format string, args ...interface{})
	Trace(format string, args ...interface{})
}
```
so you can choose to ignore everything except Error for instance.

NOTE: The output in the screenshot is not from UniDoc, looks like output from ghostscript (gs).

**Comment by jcampbell05** [comment]
Interesting so the 0.0 scale is a Unidocs issue ?

**Comment by gunnsth** [comment]
Possibly.  Depends on what was done. Can you send us the input file that caused this problem and the unidoc code that created the file?

**Comment by jcampbell05** [comment]
@gunnsth sure, I'll email it over. There is another file produced that triggers a seg-fault in ghostscript too not sure if that's worth sending over too.
