### ISSUE TITLE
Artifacts Persisting from Previous Pages

### ISSUE THREAD

**Issue by iamacarpet** [unidoc/unidoc#210]
I've been testing out the form flattening from `unidoc-examples/pdf/forms/pdf_form_flatten.go`.

When run against a complex multi-page PDF, artifacts (such as footer text, other rectangles and text from around the page) seem to persist onto other pages further down the document.

Annoyingly I can't share my examples, as they are contracts covered by an NDA.

Has anyone else spotted it when doing any testing?

**Comment by gunnsth** [comment]
@iamacarpet Hard to debug without the source PDF.  Any way you can try to reproduce on a similar/template file created through a similar process as the covered file?

Would be great to have as this code (and forms handling in general) is under active development (and only available currently in v3-enhance-forms branch).

It is planned to be included in our next major release (v3), but still needs to undergo some development (as well as testing).  If you can send us some files to work with, that would be great and aid with the development.

**Comment by iamacarpet** [comment]
Thanks @gunnsth 

I'll see what I can do.

I sent you a private email about something else an hour or so ago. It'll probably be best to provide more details in a semi-private way, so I'll send them to you there. Do you have any other way of getting in touch, like Skype or Hangouts?

**Comment by iamacarpet** [comment]
I'm not sure if it's something our side, but it seems to be a little on the slow side too.

```
$ time ./pdf_flatten . input.pdf
Total 1 processed / 0 failures

real    0m1.735s
user    0m0.000s
sys     0m0.000s
```

I'll look into it and see if I can re-create on another environment. Is it something you saw yourself?

**Comment by iamacarpet** [comment]
Your commit yesterday fixed the artifact issues. Brilliant work @gunnsth ! :)

As requested, I profiled the operation to see where the time is being taken:
[profile.pdf](https://github.com/unidoc/unidoc/files/2414492/profile.pdf)

Looks like 0.58s in `(*PdfReader)loadStructure`.

Followed by 0.42s in `(*PdfReader)FlattenFields`, mostly taken up by some zlib compression.
