### ISSUE TITLE
Add support for Text-Rendering-Mode 3 (invisible)

### ISSUE THREAD

**Issue by Luzifer** [unidoc/unidoc#221]
> As a user of the library I want to be able to open an existing PDF containing scanned images and add text to it generated through the Google Vision API. I do get coordinates and detected sniplets of text. In order to improve the search-ability of the PDF I want to add the plain text to the PDF while the user shall not see the added text but the original scanned image. Though they should be able to copy "the scanned text" after the OCR.

That's where the "invisible" (no stroke, no fill) text rendering mode comes in handy: The user will not have a visible text but is able to copy it as it is just not "decorated" with color.

**Comment by gunnsth** [comment]
That should be easy.  Just adding an extra '3 Tr' operand.  Are you looking to use the creator/Paragraph to add text?

**Comment by Luzifer** [comment]
Yepp, that's what I currently planned: Seemed to be the most easy way to add the text received from the API…

**Comment by gunnsth** [comment]
@Luzifer We have implemented this in #336  on v3 branch.  Can you try it out and see if it serves the purpose needed for OCR?
