### ISSUE TITLE
Make PDF creator output predictable

### ISSUE THREAD

**Issue by dennwc** [unidoc/unidoc#232]
When working on https://github.com/unidoc/unidoc/issues/118 I noticed that the size of the document fluctuates noticeably. This means that an output of the library is not predictable and it will generate different document given the same input.

This might be a problem for automated pipelines that involve hashing the generated document.

**Comment by dennwc** [comment]
A way to reproduce: run a `TestParagraphChinese` test in `pdf/creator/creator_test.go` with those lines added at the end:

```golang
st, _ := os.Stat("/tmp/2_p_nihao.pdf")
t.Logf("%d", st.Size())
```

Note that each time the test is run, the out files size is different.

**Comment by gunnsth** [comment]
Fixed in v3, closing.
