### ISSUE TITLE
Replace AddressStyle with NoteStyle in test

### ISSUE THREAD

**Issue by ribice** [unidoc/unidoc#295]
https://github.com/unidoc/unidoc/blob/098019ac2c16c1e1d0d7ac05f159c1111d4239cf/pdf/creator/invoice_test.go#L207

Think this should be NoteStyle() instead of AddressStyle().

**Comment by gunnsth** [comment]
@adrg Can you take a look at this one?

**Comment by gunnsth** [comment]
Closed by #297
