### ISSUE TITLE
Large bottom margin on invoices spanning over multiple pages

### ISSUE THREAD

**Issue by ribice** [unidoc/unidoc#299]
I tried to add multiple items so that invoice takes multiple page. I've noticed that on all pages, bottom margin was too big.

Example:

![image](https://user-images.githubusercontent.com/5403700/50741456-9e323780-11fd-11e9-9f00-1efb74f12133.png)

**Comment by gunnsth** [comment]
@ribice Can you verify that #301 closes the issue for the multi page invoice?

**Comment by ribice** [comment]
It is fixed:

![image](https://user-images.githubusercontent.com/5403700/50816874-39bcc880-1322-11e9-9bda-4c8d51156eb7.png)
