### ISSUE TITLE
Image position information

### ISSUE THREAD

**Issue by liming-vie** [unidoc/unidoc#315]
Hi,

How can I get all the images with their position / BBox information from PDF?

Thanks!

**Comment by gunnsth** [comment]
To accurately get the size and position you need to process the content streams and keep track of the draw position at the time when the image is drawn (Do operand).  Can be done by extending our image extraction example
https://github.com/unidoc/unidoc-examples/blob/master/pdf/image/pdf_extract_images.go

We plan to release a higher level interface for extracting images with position, size (vectorized) in the future.

**Comment by liming-vie** [comment]
> To accurately get the size and position you need to process the content streams and keep track of the draw position at the time when the image is drawn (Do operand). Can be done by extending our image extraction example
> https://github.com/unidoc/unidoc-examples/blob/master/pdf/image/pdf_extract_images.go
> 
> We plan to release a higher level interface for extracting images with position, size (vectorized) in the future.

Hi, 
I only see the Height and Width properties in XObjectImage, but cannot find the info about position.
Should I go over the codes about parser?

**Comment by gunnsth** [comment]
The `Height` and `Width` on the XObject Image actually only define the size of the image in the data, not how it displays on the PDF.

See section 8.9 (PDF32000_2008).
For instance, in 8.9.4 (Image Coordinate System), there is an example:
```
the code shown in this example paints the image in a rectangle whose lower-left corner is
at coordinates (100, 200), that is rotated 45 degrees counter clockwise, and that is 150 units wide and 80
units high.
```
```
q % Save graphics state
1 0 0 1 100 200 cm % Translate
0. 7071 0. 7071 -0. 7071 0. 7071 0 0 cm % Rotate
150 0 0 80 0 0 cm % Scale
/Image1 Do % Paint image
Q % Restore graphics state
```

Thus, you need to keep track of the graphics state, transformation matrix (defined in section 8.4).

I am working on an updated image extraction example that shows how to do this.  We plan on adding this to the `extractor` package in the near future as well.

Will post here once the example has been prepared.

**Comment by liming-vie** [comment]
Thanks a lot!!

**Comment by gunnsth** [comment]
Please try:
https://github.com/unidoc/unidoc-examples/blob/v3-image-extraction-size-position/pdf/image/pdf_extract_images2.go

Note that this has not been tested rigorously yet.  If you find any bugs, please let us know and and submit the relevant PDF files.

Note that the position information is in PDF coordinates. In PDF, the origin is in lower left corner, and X increases from 0 (left) to the right, and Y position increases from 0 (bottom) and upwards.

**Comment by liming-vie** [comment]
Thanks! It works well for me!

**Comment by gunnsth** [comment]
This will be included in the extractor package in v3.  See #317.
Will close this ticket.
