### ISSUE TITLE
How to get a image from a total page ?

### ISSUE THREAD

**Issue by lulouis** [unidoc/unidoc#316]
When I get every page from a pdf file ，I need to save a image file from a total page content.
------------------------------------------------------------------------------------
### github.com\unidoc\unidoc-examples\pdf\image\pdf_list_images.go
------------------------------------------------------------------------------------
	for i := 0; i < numPages; i++ {
		fmt.Printf("-----\nPage %d:\n", i+1)

		page, err := pdfReader.GetPage(i + 1)
		if err != nil {
			return err
		}

		// List images on the page.
		err = listImagesOnPage(page)  //Mark :How to get a image from a total page ?
		if err != nil {
			return err
		}
	}

**Comment by gunnsth** [comment]
Do you want to render the page contents to an image file?  I.e. same as it would look like in a PDF viewer?
Unfortunately that is not supported yet.

**Comment by lulouis** [comment]
@gunnsth  Yes , exactly as your example , render a Whole page to an image.

**Comment by lulouis** [comment]
@gunnsth  Thank you all the same , I found another way to do it.
