### ISSUE TITLE
unable to add digital signature on multiple pages

### ISSUE THREAD

**Issue by irahulranjan** [unidoc/unidoc#340]

**Comment by irahulranjan** [comment]
Here is the sample code that I am using.

`
func signPDF() {

	f1, err := os.Open("test.pdf")
	if err != nil {
		log.Println(err)
		return
	}
	defer f1.Close()

	pdf1, err := model.NewPdfReader(f1)
	if err != nil {
		log.Println(err)
		return
	}

	appender, err := model.NewPdfAppender(pdf1)
	if err != nil {
		log.Println(err)
		return
	}

	f, _ := ioutil.ReadFile("certificate.p12")
	privateKey, cert, err := pkcs12.Decode(f, "test2")
	if err != nil {
		log.Println(err)
		return
	}

	handler, err := sighandler.NewAdobePKCS7Detached(privateKey.(*rsa.PrivateKey), cert)
	if err != nil {
		log.Println(err)
		return
	}

	numPages, _ := pdf1.GetNumPages()
	var appearance *model.PdfAppearance

	for i := 1; i < numPages; i++ {
		_, appearance, err = appender.Sign(1, handler)
		if err != nil {
			log.Println(err)
			return
		}
	}

	v := "Signed By User"
	appearance.Signature.Name = core.MakeString("Test Appender")
	appearance.Signature.Reason = core.MakeString("TestAppenderSignPage4")
	err = NewTextSignatureAppearance(v).Apply(appearance)
	if err != nil {
		return
	}

	err = appender.WriteToFile("appender_sign_page_4.pdf")
	if err != nil {
		log.Println(err)
		return
	}
}

// SignatureAppearance is a basic signature appearance implementation for plain text.
type SignatureAppearance struct {
	text string
}

// TODO(gunnsth): Add more involved signature appearance generation.
func NewTextSignatureAppearance(text string) SignatureAppearance {
	return SignatureAppearance{text: text}
}

// Apply applies the signature appearance `sa` to `signature`.
func (sa SignatureAppearance) Apply(signature *model.PdfAppearance) error {
	resources := model.NewPdfPageResources()

	// Use Helvetica font.
	// TODO(gunnsth): Allow custom font and use font's encoder below.
	font, err := model.NewStandard14Font("Helvetica")
	if err != nil {
		return err
	}
	resources.SetFontByName("F1", font.ToPdfObject())

	cc := contentstream.NewContentCreator()
	cc.Add_q()
	cc.Add_BT()

	// Add DA operands.
	fontsize := 10.0

	cc.Add_Tf("F1", fontsize)
	cc.Add_Td(0, 3.00)
	cc.Add_Tj(*core.MakeString(sa.text))

	cc.Add_ET()
	cc.Add_Q()

	// Height and width can be tuned.
	width := 200.0
	height := 20.0
	x := 50.0 + 100
	y := 30.0 + 100

	xform := model.NewXObjectForm()
	xform.Resources = resources
	xform.BBox = core.MakeArrayFromFloats([]float64{0, 0, width, height})
	xform.SetContentStream(cc.Bytes(), core.NewRawEncoder())

	signature.Rect = core.MakeArrayFromFloats([]float64{x, y, x + width, x + height})

	apDict := core.MakeDict()
	apDict.Set("N", xform.ToPdfObject())

	signature.AP = apDict

	return nil
}`

**Comment by irahulranjan** [comment]
I also tried the following versions of the for loop:

`for i := 1; i < numPages; i++ {
		_, appearance, err := appender.Sign(i, handler)
		if err != nil {
			log.Println(err)
			return
		}

		v := "Signed By User"
		appearance.Signature.Name = core.MakeString("Test Appender")
		appearance.Signature.Reason = core.MakeString("TestAppenderSignPage4")
		err = NewTextSignatureAppearance(v).Apply(appearance)
		if err != nil {
			return
		}
	}

	err = appender.WriteToFile("appender_sign_page_4.pdf")
	if err != nil {
		log.Println(err)
		return
	}`

**Comment by gunnsth** [comment]
Thank you, we are looking into this.

One should only sign once per revision, i.e. creating a single digital signature dictionary.
However, it would be possible to create more signature fields/annotations that point to the same digital signature object.  This should already be possible, but requires some pretty low level use of the model package at the moment.

The way it could work (with some enhancements to the current support, at least #323 ):
1. Sign one page, creating the actual signature dictionary (appender.Sign).
2. Style the layout of the returned sigfield
3. Create more signature fields referring to the same signature dictionary object and defining their own appearances.

It is also worth thinking about whether the current API of Sign() to create a single form field immediately is appropriate.  Might be more flexible for Sign just to create a signature dictionary and then having methods for creating signature fields that can point to that signature dictionary.
