### ISSUE TITLE
PDF table of contents outlines

### ISSUE THREAD

**Issue by prprprus** [unidoc/unidoc#359]
Hi.

This library is awesome. Can it be used to create PDF catalog?

**Comment by gunnsth** [comment]
Hi.  Can you clarify what you mean by creating a PDF catalog?

**Comment by prprprus** [comment]
table of chapter, [like this](https://raw.githubusercontent.com/prprprus/picture/master/table_of_chapter.png)

**Comment by gunnsth** [comment]
This is actually called `outlines` in PDF terminology.
There is already low level support for this in the `model` schema package.
The creator package by default uses this to automatically create a table of contents for each chapter, see for instance:
https://github.com/unidoc/unidoc/blob/4bb53f7b4b6c3bd9117abd59a913cf6188397446/pdf/creator/chapters.go#L177
