### ISSUE TITLE
Long tables not wrapping properly across pages

### ISSUE THREAD

**Issue by bgetsug** [unidoc/unidoc#380]
Hi, I just started working with unidoc this week and I've run into a bit of a snag. When creating a PDF with a long table, where the rows need to wrap across pages, the table breaks aren't occurring in the correct places, leaving a lot of whitespace at the bottom of each page.

I've created a repository where I've replicated the issue: https://github.com/s2nventures/unidoc-test

I'm using [a fork](https://github.com/s2nventures/unidoc/tree/table-improvements) with [my attempt at resolving](https://github.com/unidoc/unidoc/compare/master...s2nventures:table-improvements) #374, but that doesn't appear to be causing the issue. It _feels_ like it has something to do with the content that I've placed before the long table, as I was unable to replicate the issue when the long table is the first block in the PDF.

I'm hoping that someone can take a look at my code and let me know if I'm doing something incorrectly, or if this is indeed, a bug. Thank you.

**Comment by bgetsug** [comment]
Output from my test repo: [really_long_table.pdf](https://github.com/unidoc/unidoc/files/3000016/really_long_table.pdf)

**Comment by adrg** [comment]
@bgetsug I noticed you are using the master branch. Please use the v3 branch as the issue is resolved there.

I've uploaded the example from your repository adapted for the v3 branch.
[unidoc_test.zip](https://github.com/unidoc/unidoc/files/3005306/unidoc_test.zip)

**Comment by bgetsug** [comment]
@adrg v3 is working much better, thank you!
