### ISSUE TITLE
support convert  pdf to word?

### ISSUE THREAD

**Issue by zouhuigang** [unidoc/unidoc#42]
support convert  pdf to word?

**Comment by gunnsth** [comment]
This is part of our future vision, but not a current feature.

If anyone is interested in undertaking this project we would be happy to consider working together.
UniDoc v2 is becoming mature enough to have the features needed to parse and process the content stream as needed for this.  Support for fonts would be needed as well as a strategy for creating the docx file.

The most basic way is to take all text that appears in the content stream and place in a textbox with a given coordinate position.  Same for images.  This can yield a good looking Word docx file, but is not easy to work with/edit.  This can be a good starting point though and then grouping the text more intelligently together so it can be edited would be a second step.

**Comment by zouhuigang** [comment]
Thank you for your answer
