### ISSUE TITLE
TestAppenderSignMultiple produces invalid signature fields, annotations

### ISSUE THREAD

**Issue by sayhei** [unidoc/unidoc#449]
this is related to [bug](https://github.com/unidoc/unidoc-examples/issues/41)

**Comment by gunnsth** [comment]
It appears that the `P` entries of the signature fields are pointing to different page objects and there are copies of the page objects.  The test case should be expanded to check the structure and catch the bug also.

**Comment by gunnsth** [comment]
#474 addresses this issue.
