### ISSUE TITLE
Make it easy to use color values for r,g,b 0-255 or hex color codes

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unidoc#63]
# Current state

Currently the values are in range 0-1 (floating point), like is used in PDF.  E.g. to make a red paragraph

```
p := NewParagraph("Red paragraph")
p.SetColorRGB(1.0, 0, 0)
```

# Disadvantage

Many developers are probably expecting this to be 0-255 (byte).  Although, it is worth noting that there is a lot of definitions regarding colors and their value, see https://en.wikipedia.org/wiki/RGB_color_model

Many are also used to colors represented by hex values, e.g. "#ffffff" for white

# Proposed change

1. Create a more generic SetColor function that can accept a more generic color object:

`func (p *paragraph) SetColor(val color) {}`

where color is an object.

This also opens up possibilities to add support for more colorspaces in the future and is compatible with PDF functions where color is very generic.

2. Create color creating objects:

```
func ColorRGBFromArithmetic(r,g,b float64) color
func ColorRGBFrom8bit(r,g,b byte) color
func ColorRGBFromHex(code string) color
```
where the arithmetic is with each component in range 0-1

Then the new syntax will be

```
p := NewParagraph("Red paragraph")
p.SetColor(creator.ColorRGBFromHex("#ff0000"))
```

or

```
p := NewParagraph("Red paragraph")
p.SetColor(creator.ColorRGBFrom8Bit(255, 0, 0))
```

This will also avoid confusion, such as inputing 255 into a function with range 0-1.

**Comment by ahall** [comment]
I like having a Color object.

**Comment by gunnsth** [comment]
Agreed, will change the proposal to the specified alternative.
