### ISSUE TITLE
Change NewTable to only specify columns, can add rows as needed.

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unidoc#66]
# Current state
Currently need to specify M x N rows when creating a table, like so:

`table := NewTable(4, 4) // 4x4 table `

# Disadvantages

This means that one needs to add the correct amount of rows in the beginning.  In most cases, that should not be very hard, but when generating tables with multiple functions, could be somewhat tedious.

Also, internally, there is should be no need to know the row count ahead of drawing.

# Proposed changes

1. Change

`func NewTable(rows, cols int) *Table {`

to

`func NewTable(cols int) *Table {`

2. For inserting new cells, rename:

`func (table *Table) NewCell(row, col int) *tableCell {`

to

`func (table *Table) NewCellAt(row, col int) *tableCell {`

3. Add a new function to add new cells:

`func (table *Table) NewCell() *tableCell {`

which just adds a new cell at the current position.

Calling this first goes at row1,col1, calling again goes to row1,col2, ...  when it goes beyond the column count, then wraps to the first column of a new row.

4. Also add:

`func (table *Table) SkipCells(cells int)`

which allows skipping over cells (no content)

5. Then add a new function:

`func (table *Table) NewRow()`

creates a new row, and moves the cell index to its first cell.

**Comment by ahall** [comment]
Nice and intuitive!

**Comment by gunnsth** [comment]
Instead of NewCellAt(row, col int) function, where the main intention is to make it easy to place content at specific row, column, added convenience functions to skip back and forth:

The following functions can skip over N many cells, or N many rows, or N many rows and columns.  SkipOver can take negative columns (as long as row>1).  Does not support going moving back, table generation is all forward generated.

```
func (table *Table) SkipCells(num int)
func (table *Table) SkipRows(num int)
func (table *Table) SkipOver(rows, cols int)
```
