### ISSUE TITLE
Add support for a dotted line separator

### ISSUE THREAD

**Issue by ahall** [unidoc/unidoc#75]
When creating table of contents it would be useful being able to have a dotted line between the chapter name and the page name. Also be good if this was configurable so one could use a dashed line or something else to separate.

**Comment by gunnsth** [comment]
Currently, the only solution for drawing lines is the creator's NewLine function which can draw a line with specified coordinates.  At the moment it does not have a dotted line style, but that can be easily added.

To draw this kind of separator, the tricky part is knowing where to place the line and how long it needs to be.  Clearly it would need knowledge about both the chapter name, the page number, and the alignment information, as well as the desire to make it fill up the line.

This basically calls for some new content wrapper/container which is similar to a table row, but can have a width that grows.  LateralContainer, or InlineBlock / InlineContainer / InlineWrapper, which is a mode where the objects are placed next to each other.  Another way could be to set a Position: inline mode in the context.  But this may only serve to complicate things.  Both approaches need to be considered.

The syntax for approach 1 would be along the lines of:
```
	inlineWrapper := creator.NewInlineWrapper()
	chapName := creator.NewParagraph("Chapter name")
	pageNum := creator.NewParagraph("1")
	separator := creator.NewDottedLineSeparator()
	separator.SetLength(c.Context().Width - chapName.Width() - pageNum.Width())
	inlineWrapper.Add(chapName)
	inlineWrapper.Add(separator)
	inlineWrapper.Add(pageNum)
	c.Draw(inlineWrapper)
```

whereas the syntax for approach 2 would be:
	```
inlineWrapper := creator.NewInlineWrapper()
	chapName := creator.NewParagraph("Chapter name")
	pageNum := creator.NewParagraph("1")

	c.SetDrawMode(creator.DrawModeInline)
	c.Draw(chapName)
	separator := creator.NewDottedLineSeparator()
	separator.SetLength(c.Context().Width - c.Context().X - pageNum.Width())
	c.Draw(separator)
	c.Draw(pageNum)

	// Go back to default draw mode.
	c.SetDrawMode(creator.DrawModeBlock)
```

Comments on these approaches would be appreciated.  And other suggestions are welcomed.

**Comment by gunnsth** [comment]
To do this:
1. Need to implement Width() and Height() to be a VectorDrawable (needed for Division).
Let Width() return 0  // Same idea as Width() for Division component
Let Height() return the height of the   Division component which should be fixed (depends on point size).

2. GeneratePageBlocks(ctx DrawContext) knows how much space there is available based on ctx.Width

3. The Divison component needs to detect that the component is a separator (e.g. type check) and when in inline mode it should check the width of the following component and subtract it from the available width (ctx.Width) that is passed to the DottedLineSeparator component.

When not in inline mode, the separator should fill the entire width.  In inline mode, if there is no component to the right, it should reach all the way to the right.

**Comment by ahall** [comment]
The use case I had was to generate table of contents which was satisfied by the work done in #55 .
