### ISSUE TITLE
CREATOR: Support for encrypting document with a password

### ISSUE THREAD

**Issue by ahall** [unidoc/unidoc#76]

**Comment by gunnsth** [comment]
# Proposed solution
Add a hook which exposes the PdfWriter instance prior to writing.  This will make it possible to add a password and other things that can be done with access to the PdfWriter.  E.g.
```
c.SetPdfWriterAccessFunc(func(w *model.PdfWriter) error {
	userPass := []byte("password")
	ownerPass := []byte("password")
	err := w.Encrypt(userPass, ownerPass, nil)
	return err
})
```

This will also enable other use cases where the PdfWriter needs to be accessed prior to writing.
