### ISSUE TITLE
Creator: Force pagebreaks in chapter/subchapter

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unidoc#86]
# Current state
Currently page breaks can be forced with c.NewPage()

# Challenge

This does not work with chapters/subchapter/table or other wrapped Drawables.
These are drawn in their entirety when drawn with c.Draw(..)

# Suggested solution

Make a new Drawable, PageBreak which can be created creator.NewPageBreak() and can be added to a chapter/subchapter/table (and others that make sense).

When drawing the Drawable, will force going to next page upon encouring the PageBreak drawable.

**Comment by llonchj** [comment]
@gunnsth any update on this?

**Comment by gunnsth** [comment]
@llonchj Unfortunately, I haven't had a chance to review your pr #142 yet, but hope to do soon. At first glance everything looks good, just need to get a chance to test it and merge.  I will try to get this done soon.

**Comment by gunnsth** [comment]
@llonchj I have merged your PR with a few fixes.  Would be great if you test if it works out as needed for your purposes.
